/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("hu.bme.kotlin-application-conventions")
}

dependencies {

}

application {
    // Define the main class for the application.
    mainClass.set("hu.bme.app.AppKt")
}
