/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hu.bme.app

fun main() {

    val prologCode = """
parent(anne, bob).
parent(bob, carol).
ancestor(X, Y) :- parent(X, Y).
ancestor(X, Y) :- parent(X, Z), ancestor(Z, Y).
    """.trimIndent()

    val clauses = Parser.parseProlog(prologCode)
    clauses.forEach { println(it) }
    val mapping = createMapping(clauses)

    mapping.forEach { (name, index) ->
        println("$name: $index")
    }

    clauses.filter { it.body.isEmpty() }.forEach { clause ->
        println(clause.head.encode(mapping)) }
}
